use comp;
use chatbot;
select * from laptop;
select * from attention;
select * from discount;
select * from users;
insert into attention value(13 , 'leo326567777777');
insert into users value('leo326567777777');
insert into discount value(13,40000,'2019-11-27 ','2019-11-28 ');
insert into users select "Jacky" where "Jacky" not in (select userID from users);
alter table attention drop foreign key attention_ibfk_2;
alter table users modify userID varchar(100);
alter table attention modify att_userID varchar(100);
alter table attention drop foreign key userFK;
alter table attention add constraint userFK foreign key(att_userID) references users(userID);
select * from users;
select * from laptop where GPU = "Intel UHD Graphics 620";
select * from laptop where price < 50000;
select * from laptop;
select * from users;
select * from attention;
delete from attention where att_userID = "U3a650bac5a18cc1f4c0b7156070f6614" and att_NO in (select lapNO from laptop where lapPrice >= 40000);
select * from discount where end >= "2019-11-28";
select * from discount where disprice = 28900;
select * from users where userID = "lucy";
select * from attention where attuserID = "Jack" and lapID = "ZenBook Flip 13 UX362FA (i5-8265U) 皇家藍";
Select lapID, disprice, CPU, GPU from laptop, discount where lapID = ID and disprice < 40000 order by disprice;
select ID,price-5000,Date("2019-12-03"),Date("2019-12-28") from laptop;
insert into discount(lapID,disprice,start,end) select ID,price-5000,Date("2019-12-03"),Date("2019-12-28") from laptop;
insert into users value("lucy");
insert into users value("Jack");
insert into users value("jin");
insert into attention(lapID,attuserID) select ID,userID from laptop,users where userID = "lucy" and price < 40000;
insert into attention(lapID,attuserID) select ID,userID from laptop,users where userID = "Jack" and price between 30000 and 40000;
insert into attention(lapID,attuserID) select ID,userID from laptop,users where userID = "leo326567777777" and price > 30000;
delete from attention where attuserID = "leo326567777777";
delete from attention where attuserID = "lucy";
delete from attention where attuserID = "Jack";

select ID,CPU, attuserID  from laptop,attention where ID = lapID and CPU like "%Intel® Core™ i5%";
select a.lapID,disprice,attuserID,CPU from discount as d,attention as a,laptop where attuserID = "Jack" and a.lapID = d.lapID and ID = a.lapID;
select distinct userID from users,laptop,attention where ID = lapID and attuserID = userID and CPU like "%i7%";
select count(*) from users;
select max(price),ID from laptop;
select userID from users where userID not in (select distinct attuserID from attention);
insert into discount(lapID,disprice,start,end) value("ZenBook Flip 13 UX362FA (i5-8265U) 皇家藍",20000,"2019-12-22",null);
select lapID, disprice,start,end from discount where end is null;
select ID from laptop where CPU like "%i7%";
select ID ,attuserID, GPU, start, end from discount as d,attention as a,laptop where ID = d.lapID and ID = a.lapID and attuserID = "Jack" and CURDATE() between start and end;
alter table laptop add column mark varchar(100);
alter table laptop modify image varchar(100);
alter table users add column name varchar(100);
alter table attention drop foreign key attention_ibfk_1;
alter table attention add constraint lapIDFK foreign key(lapID) references laptop(ID);
alter table discount drop foreign key discount_ibfk_1;
alter table discount add constraint DlapIDFk foreign key(lapID) references laptop(ID);
show columns from laptop;
show columns from users;

select * from discount;
insert into discount select lapNO,(lapprice - 5000),"2019-12-01","2019-12-26" from laptop where lapprice < 30000;
select * from laptop;
delete from discount where disNO = 13;
select lapNO from laptop left join discount on lapNO = disNO;
select lapPrice from laptop left join discount on lapNO = disNO;
select if(lapNO in (select disNO from discount where CURDATE() between disStart and disEnd),disprice,lapPrice) as Price from laptop left join discount on lapNO = disNO;
select distinct lapNO,lapID,if(lapNO in (select disNO from discount where CURDATE() between disStart and disEnd),disprice,lapPrice) as lapPrice,lapCPU,lapGPU,lapRAM,lapDisk,lapWarranty,lapImage,lapBrand from laptop left join discount on lapNO = disNO where if(lapNO in (select lapNO from laptop left join discount on lapNO = disNO where CURDATE() between disStart and disEnd),lapNO = disNO,lapNO) and lapPrice>=30000;
insert into attention(att_NO,att_userID)select lapNO,"U0f8e2c16e503bd18abd93d0d3e644866" from laptop where lapNo = 5;
select lapNO from laptop,discount where lapNO = disNO and CURDATE() between disStart and disEnd;
SELECT IF(500>1000, lapNO, lapprice) from laptop;

